# Generated by Django 4.1.2 on 2022-12-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('curso', models.CharField(default='', max_length=30)),
                ('userName', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
