# Generated by Django 4.1 on 2022-12-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=20)),
                ("apellido", models.CharField(default="", max_length=20)),
                ("titulo", models.CharField(default="", max_length=30)),
                ("userName", models.CharField(default="", max_length=30)),
                ("password", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
