# Generated by Django 4.1.2 on 2022-12-17 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(default='', max_length=45)),
                ('calle', models.CharField(max_length=45)),
                ('numero', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=45)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=45)),
                ('password', models.CharField(default='', max_length=45)),
                ('nombre', models.CharField(default='', max_length=45)),
                ('apellidoPaterno', models.CharField(default='', max_length=45)),
                ('apellidoMaterno', models.CharField(default='', max_length=45, null=True)),
                ('nacimiento', models.DateField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.direccion')),
                ('institucion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.institucion')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
