# Generated by Django 4.1.2 on 2022-12-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alumno_asignatura_curso_profesor_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='promedio',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateTimeField(default=''),
        ),
    ]
