# Generated by Django 4.1.2 on 2022-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_alumno_promedio_alter_calificacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
