# Generated by Django 4.1.2 on 2022-12-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='id',
            field=models.ManyToManyField(to='app.user'),
        ),
    ]
