# Generated by Django 4.1 on 2022-12-20 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_user_nacimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="user",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
