# Generated by Django 4.1.2 on 2022-12-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_profesor_user_alter_profesor_id'),
        ('app', '0010_alter_calificacion_fecha'),
    ]

    operations = [
    ]
